/*
THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF PARALLAX
SOFTWARE CORPORATION ("PARALLAX").  PARALLAX, IN DISTRIBUTING THE CODE TO
END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.  
COPYRIGHT 1993-1998 PARALLAX SOFTWARE CORPORATION.  ALL RIGHTS RESERVED.
*/
/*
 * $Source: Smoke:miner:source:main::RCS:RADAR.H $
 * $Revision: 1.1 $
 * $Author: allender $
 * $Date: 1995/05/16 16:01:43 $
 * 
 * Prototypes for radar.
 * 
 * $Log: RADAR.H $
 * Revision 1.1  1995/05/16  16:01:43  allender
 * Initial revision
 *
 * Revision 1.3  1994/07/07  14:59:03  john
 * Made radar powerups.
 * 
 * 
 * Revision 1.2  1994/07/06  19:36:36  john
 * Initial version of radar.
 * 
 * Revision 1.1  1994/07/06  17:22:18  john
 * Initial revision
 * 
 * 
 */



#ifndef _RADAR_H
#define _RADAR_H

void radar_render_frame();

#endif
